### ISSUE TITLE
ImportError: cannot import name HAProxyServer

### ISSUE THREAD

**Issue by sivakumarvaddi786** [bcicen/haproxy-stats#8]
error observed in Python 2.7.17 and Python 3.6.9 and works fine with Python 2.7.12

Traceback (most recent call last):
  File "lb.py", line 3, in <module>
    from haproxystats import HAProxyServer
ImportError: cannot import name HAProxyServer
